apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: eureka
  namespace: ms
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`eureka.ctnrs.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: eureka
      port: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: ms
spec:
  clusterIP: None
  ports:
  - port: 8888
    name: eureka 
  selector:
    project: ms
    app: eureka

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: ms 
spec:
  replicas: 3
  selector:
    matchLabels:
      project: ms
      app: eureka
  serviceName: "eureka"
  template:
    metadata:
      labels:
        project: ms 
        app: eureka
    spec:
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - name: eureka
        image: registry.wzxmt.com/microservice/eureka:latest
        ports:
          - protocol: TCP
            containerPort: 8888
        env:
          - name: JAVA_OPTS
            value: "-Xmx1g"
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        # resources:
        #   requests:
        #     cpu: 0.5
        #     memory: 256Mi
        #   limits:
        #     cpu: 1 
        #     memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 60
          periodSeconds: 10
